-- dekompiliert aus sta_entropointix.sco
-- Quelle laut Bytecode: =(none)

True = 1
False = 0
F = 1
N = 2
U = 3
E = 4
VesselGotoLib = LoadLib("VesselGoto")
VesselAttackLib = LoadLib("VesselAttack")
SensorLib = LoadLib("Sensor")
MiscLib = LoadLib("Misc")
TurretLib = LoadLib("Turret")
VehicleGotoLib = LoadLib("VehicleGoto")
VehicleAttackLib = LoadLib("VehicleAttack")
DockLib = LoadLib("Dock")
FormationLib = LoadLib("Formation")
CameraLib = LoadLib("Camera")
DipolLib = LoadLib("Dipol")
OldOneLib = LoadLib("OldOne")
SED_SetTaskTextKey = function(L0, L1, L2)
  Game_SetTaskTextKey(GetGameNode(), L0, L1, L2)
end
__InitLayout = function()
  node0 = Node_Find("/")
  Game_LoadProgress_Advance(node0)
  node1 = Node_CreateNode("nod_terrain", "Terrain")
  Node_AddSon(node0, node1)
  Terrain_LoadTerrain(node1, "map/1N2/Terrain/")
  Node_EnterSimulation(node1)
  Game_LoadFog(node0, "map/1N2/Fog/fog.fog")
  Game_SetFog(node0, 0.99, 1)
  Game_SetCausticTerrain(node0, 0.025, 0.3)
  Game_SetCausticObject(node0, 0.1, 0.3)
  Game_SetCausticBuilding(node0, 0.025, 0.3)
  Game_SetLightCache(node0, "map/1N2/Lmsh/", "map/1N2/Ltex/")
  Game_SetTerrainDepth(node0, 2024)
  Game_SetDecompressionHeight(node0, 600)
  Game_SetAmbientLight(node0, 0.105882, 0.32549, 0)
  Game_SetParallelLightT(node0, 0.211765, 0.65098, 0)
  Game_SetParallelLightB(node0, 0.564706, 0.392157, 0.188235)
  Game_LoadTextTable(node0, "dat/sty/pilot_d.des")
  Game_LoadTextTable(node0, "dat/sty/cargo_d.des")
  Game_LoadProgress_Advance(node0)
  node2 = Node_CreateNode("NOD_Scenario", "Scenario_Static")
  Node_AddSon(node0, node2)
  Node_EnterSimulation(node2)
  Game_LoadProgress_Advance(node0)
  node3 = Node_CreateNode("NOD_Directory", "Light")
  Node_AddSon(node2, node3)
  Node_EnterSimulation(node3)
  Game_LoadProgress_Advance(node0)
  node4 = Node_CreateNode("NOD_Directory", "Navigation")
  Node_AddSon(node2, node4)
  Node_EnterSimulation(node4)
  Game_LoadProgress_Advance(node0)
  node5 = Node_CreateNode("NOD_Directory", "Director")
  Node_AddSon(node2, node5)
  Node_EnterSimulation(node5)
  Game_LoadProgress_Advance(node0)
  node6 = Node_CreateNode("NOD_Directory", "Trigger")
  Node_AddSon(node2, node6)
  Node_EnterSimulation(node6)
  Game_LoadProgress_Advance(node0)
  node7 = Node_CreateNode("NOD_Directory", "Object")
  Node_AddSon(node2, node7)
  Node_EnterSimulation(node7)
  Game_LoadProgress_Advance(node0)
  node8 = Node_CreateNode("nod_generic", "SpStern_1")
  Node_AddSon(node7, node8)
  Body_SetCS(node8, MAT_Vector3(635.2062, 3028.362, 662.4882), MAT_Vector3(-28.2113, 0, 0))
  Node_ParseIniFile(node8, "osd/ent/ent_jumpstar.osd")
  Body_SetFriendOrFoeID(node8, 0)
  Body_SetNameKey(node8, -1)
  Body_SetCargoKey(node8, -1, 0)
  Body_SetCargoKey(node8, -1, 1)
  Body_SetCargoKey(node8, -1, 2)
  Node_EnterSimulation(node8)
  Game_LoadProgress_Advance(node0)
  node9 = Node_CreateNode("nod_fx_plankton", "fx_plankton_green_1")
  Node_AddSon(node7, node9)
  Node_ParseIniFile(node9, "osd/fx_plankton/fx_plankton_green.osd")
  Node_EnterSimulation(node9)
  Game_LoadProgress_Advance(node0)
  node10 = Node_CreateNode("nod_fx_rays", "fx_rays_01_1")
  Node_AddSon(node7, node10)
  Node_ParseIniFile(node10, "osd/fx_rays/fx_rays_01.osd")
  Node_EnterSimulation(node10)
  Game_LoadProgress_Advance(node0)
  node11 = Node_CreateNode("nod_fx_sky", "fx_sky_13_1")
  Node_AddSon(node7, node11)
  Node_ParseIniFile(node11, "osd/fx_sky/fx_sky_13.osd")
  Node_EnterSimulation(node11)
  Game_LoadProgress_Advance(node0)
  node12 = Node_CreateNode("nod_fx_plant", "coral_01_1")
  Node_AddSon(node7, node12)
  Node_ParseIniFile(node12, "osd/fx_plant/coral_01.osd")
  FX_Plant_SetMap(node12, "map/1N2/Terrain/coral_01.tga")
  Node_EnterSimulation(node12)
  Game_LoadProgress_Advance(node0)
  node13 = Node_CreateNode("nod_fx_plant", "grass_01_1")
  Node_AddSon(node7, node13)
  Node_ParseIniFile(node13, "osd/fx_plant/grass_01.osd")
  FX_Plant_SetMap(node13, "map/1N2/Terrain/grass_01.tga")
  Node_EnterSimulation(node13)
  Game_LoadProgress_Advance(node0)
  node14 = Node_CreateNode("nod_fx_plant", "stone_01_1")
  Node_AddSon(node7, node14)
  Node_ParseIniFile(node14, "osd/fx_plant/stone_01.osd")
  FX_Plant_SetMap(node14, "map/1N2/Terrain/stone_01.tga")
  Node_EnterSimulation(node14)
  Game_LoadProgress_Advance(node0)
  node15 = Node_CreateNode("nod_fungus", "fungus_02_1")
  Node_AddSon(node7, node15)
  Body_SetCS(node15, MAT_Vector3(798.265117, 2654.452443, 450), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node15, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node15, 0)
  Node_EnterSimulation(node15)
  Game_LoadProgress_Advance(node0)
  node16 = Node_CreateNode("nod_fungus", "fungus_02_2")
  Node_AddSon(node7, node16)
  Body_SetCS(node16, MAT_Vector3(838.448097, 2701.332586, 500), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node16, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node16, 0)
  Node_EnterSimulation(node16)
  Game_LoadProgress_Advance(node0)
  node17 = Node_CreateNode("nod_fungus", "fungus_02_3")
  Node_AddSon(node7, node17)
  Body_SetCS(node17, MAT_Vector3(871.933914, 2637.709535, 400), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node17, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node17, 0)
  Node_EnterSimulation(node17)
  Game_LoadProgress_Advance(node0)
  node18 = Node_CreateNode("nod_fungus", "fungus_02_4")
  Node_AddSon(node7, node18)
  Body_SetCS(node18, MAT_Vector3(855.191005, 3381.094665, 408.799872), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node18, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node18, 0)
  Node_EnterSimulation(node18)
  Game_LoadProgress_Advance(node0)
  node19 = Node_CreateNode("nod_fungus", "fungus_02_5")
  Node_AddSon(node7, node19)
  Body_SetCS(node19, MAT_Vector3(922.162639, 3364.351757, 459.426918), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node19, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node19, 0)
  Node_EnterSimulation(node19)
  Game_LoadProgress_Advance(node0)
  node20 = Node_CreateNode("nod_fungus", "fungus_02_6")
  Node_AddSon(node7, node20)
  Body_SetCS(node20, MAT_Vector3(878.631077, 3320.820195, 354.731181), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node20, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node20, 0)
  Node_EnterSimulation(node20)
  Game_LoadProgress_Advance(node0)
  node21 = Node_CreateNode("nod_fungus", "fungus_02_7")
  Node_AddSon(node7, node21)
  Body_SetCS(node21, MAT_Vector3(1370.872582, 2604.223718, 269.413984), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node21, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node21, 0)
  Node_EnterSimulation(node21)
  Game_LoadProgress_Advance(node0)
  node22 = Node_CreateNode("nod_fungus", "fungus_02_8")
  Node_AddSon(node7, node22)
  Body_SetCS(node22, MAT_Vector3(1269.665147, 2740.729591, 67.297196), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node22, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node22, 0)
  Node_EnterSimulation(node22)
  Game_LoadProgress_Advance(node0)
  node23 = Node_CreateNode("nod_fungus", "fungus_02_9")
  Node_AddSon(node7, node23)
  Body_SetCS(node23, MAT_Vector3(2088.217606, 2844.03602, 13.436167), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node23, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node23, 0)
  Node_EnterSimulation(node23)
  Game_LoadProgress_Advance(node0)
  node24 = Node_CreateNode("nod_fungus", "fungus_02_10")
  Node_AddSon(node7, node24)
  Body_SetCS(node24, MAT_Vector3(2195.633829, 2868.78374, 12), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node24, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node24, 0)
  Node_EnterSimulation(node24)
  Game_LoadProgress_Advance(node0)
  node25 = Node_CreateNode("nod_fungus", "fungus_02_11")
  Node_AddSon(node7, node25)
  Body_SetCS(node25, MAT_Vector3(1876.337803, 3142.049105, 35), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node25, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node25, 0)
  Node_EnterSimulation(node25)
  Game_LoadProgress_Advance(node0)
  node26 = Node_CreateNode("nod_fungus", "fungus_02_12")
  Node_AddSon(node7, node26)
  Body_SetCS(node26, MAT_Vector3(1982.283812, 3173.078878, 50), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node26, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node26, 0)
  Node_EnterSimulation(node26)
  Game_LoadProgress_Advance(node0)
  node27 = Node_CreateNode("nod_fungus", "fungus_02_13")
  Node_AddSon(node7, node27)
  Body_SetCS(node27, MAT_Vector3(3158.005738, 1098.934311, 180), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node27, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node27, 0)
  Node_EnterSimulation(node27)
  Game_LoadProgress_Advance(node0)
  node28 = Node_CreateNode("nod_fungus", "fungus_02_14")
  Node_AddSon(node7, node28)
  Body_SetCS(node28, MAT_Vector3(3159.729348, 1035.830261, 150), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node28, "osd/fungus/fungus_02.osd")
  Body_SetFriendOrFoeID(node28, 0)
  Node_EnterSimulation(node28)
  Game_LoadProgress_Advance(node0)
  node29 = Node_CreateNode("NOD_Scenario", "Scenario_Dynamic")
  Node_AddSon(node0, node29)
  Node_EnterSimulation(node29)
  Game_LoadProgress_Advance(node0)
  node30 = Node_CreateNode("NOD_Directory", "Light")
  Node_AddSon(node29, node30)
  Node_EnterSimulation(node30)
  Game_LoadProgress_Advance(node0)
  node31 = Node_CreateNode("NOD_Directory", "Navigation")
  Node_AddSon(node29, node31)
  Node_EnterSimulation(node31)
  Game_LoadProgress_Advance(node0)
  node32 = Node_CreateNode("NOD_PatrolArea", "FightArea_1")
  Node_AddSon(node31, node32)
  PatrolArea_SetPosition(node32, MAT_Vector3(3577.342, 1090.558, -10))
  PatrolArea_SetRadius(node32, 512)
  PatrolArea_SetMinZ(node32, 0)
  PatrolArea_SetMaxZ(node32, 750)
  Game_LoadProgress_Advance(node0)
  node33 = Node_CreateNode("NOD_Path", "FregattePath_1")
  Node_AddSon(node31, node33)
  Game_LoadProgress_Advance(node0)
  node34 = Node_CreateNode("NOD_Position", "pos_1")
  Node_AddSon(node33, node34)
  Position_SetPosition(node34, MAT_Vector3(392.458682, 2883.973261, 350))
  Position_SetRadius(node34, 5)
  Game_LoadProgress_Advance(node0)
  node35 = Node_CreateNode("NOD_Position", "pos_2")
  Node_AddSon(node33, node35)
  Position_SetPosition(node35, MAT_Vector3(645.177583, 2755.2517, 350))
  Position_SetRadius(node35, 5)
  Game_LoadProgress_Advance(node0)
  node36 = Node_CreateNode("NOD_Position", "pos_3")
  Node_AddSon(node33, node36)
  Position_SetPosition(node36, MAT_Vector3(866.01139, 2899.325382, 350))
  Position_SetRadius(node36, 5)
  Game_LoadProgress_Advance(node0)
  node37 = Node_CreateNode("NOD_Position", "pos_4")
  Node_AddSon(node33, node37)
  Position_SetPosition(node37, MAT_Vector3(867.192275, 3191.014715, 350))
  Position_SetRadius(node37, 5)
  Game_LoadProgress_Advance(node0)
  node38 = Node_CreateNode("NOD_Position", "pos_5")
  Node_AddSon(node33, node38)
  Position_SetPosition(node38, MAT_Vector3(632.187292, 3305.56523, 350))
  Position_SetRadius(node38, 5)
  Game_LoadProgress_Advance(node0)
  node39 = Node_CreateNode("NOD_Position", "pos_6")
  Node_AddSon(node33, node39)
  Position_SetPosition(node39, MAT_Vector3(380.649346, 3167.396265, 350))
  Position_SetRadius(node39, 5)
  Game_LoadProgress_Advance(node0)
  node40 = Node_CreateNode("NOD_Directory", "Director")
  Node_AddSon(node29, node40)
  Node_EnterSimulation(node40)
  Game_LoadProgress_Advance(node0)
  node41 = Node_CreateNode("NOD_Directory", "Trigger")
  Node_AddSon(node29, node41)
  Node_EnterSimulation(node41)
  Game_LoadProgress_Advance(node0)
  node42 = Node_CreateNode("NOD_Trigger", "TriggerPresence_1")
  Node_AddSon(node41, node42)
  Body_SetFriendOrFoeID(node42, 3)
  Body_SetPosition(node42, MAT_Vector3(3578.097663, 1088.86917, 210.078073))
  Trigger_SetPresenceSphere(node42, 700)
  Node_EnterSimulation(node42)
  Game_LoadProgress_Advance(node0)
  node43 = Node_CreateNode("NOD_Trigger", "TriggerPresence_2")
  Node_AddSon(node41, node43)
  Body_SetFriendOrFoeID(node43, 3)
  Body_SetPosition(node43, MAT_Vector3(3640.074675, 1314.773233, 213.954305))
  Trigger_SetPresenceSphere(node43, 40)
  Node_EnterSimulation(node43)
  Game_LoadProgress_Advance(node0)
  node44 = Node_CreateNode("NOD_Directory", "Object")
  Node_AddSon(node29, node44)
  Node_EnterSimulation(node44)
  Game_LoadProgress_Advance(node0)
  node45 = Node_CreateNode("NOD_Directory", "TRAFFIC")
  Node_AddSon(node44, node45)
  Node_EnterSimulation(node45)
  Game_LoadProgress_Advance(node0)
  node46 = Node_CreateNode("nod_vessel", "ent_jumpship_1")
  Node_AddSon(node45, node46)
  Body_SetCS(node46, MAT_Vector3(364.678359, 2537.381048, 700.861157), MAT_Vector3(-28.612028, 0, 0))
  Node_ParseIniFile(node46, "osd/ent/ent_jumpship.osd")
  Body_SetFriendOrFoeID(node46, 0)
  Body_SetNameKey(node46, -1)
  Body_SetCargoKey(node46, -1, 0)
  Body_SetCargoKey(node46, -1, 1)
  Body_SetCargoKey(node46, -1, 2)
  Node_EnterSimulation(node46)
  Game_LoadProgress_Advance(node0)
  node47 = Node_CreateNode("nod_vessel", "ent_jumpship_2")
  Node_AddSon(node45, node47)
  Body_SetCS(node47, MAT_Vector3(1186.605235, 3065.256424, 700.8612), MAT_Vector3(93.266551, 0, 0))
  Node_ParseIniFile(node47, "osd/ent/ent_jumpship.osd")
  Body_SetFriendOrFoeID(node47, 0)
  Body_SetNameKey(node47, -1)
  Body_SetCargoKey(node47, -1, 0)
  Body_SetCargoKey(node47, -1, 1)
  Body_SetCargoKey(node47, -1, 2)
  Node_EnterSimulation(node47)
  Game_LoadProgress_Advance(node0)
  node48 = Node_CreateNode("nod_vessel", "ent_jumpship_3")
  Node_AddSon(node45, node48)
  Body_SetCS(node48, MAT_Vector3(313.898202, 3484.485923, 700.8612), MAT_Vector3(-145.073711, 0, 0))
  Node_ParseIniFile(node48, "osd/ent/ent_jumpship.osd")
  Body_SetFriendOrFoeID(node48, 0)
  Body_SetNameKey(node48, -1)
  Body_SetCargoKey(node48, -1, 0)
  Body_SetCargoKey(node48, -1, 1)
  Body_SetCargoKey(node48, -1, 2)
  Node_EnterSimulation(node48)
  Game_LoadProgress_Advance(node0)
  node49 = Node_CreateNode("nod_vessel", "atl_fregatte_1")
  Node_AddSon(node45, node49)
  Body_SetCS(node49, MAT_Vector3(464.519372, 3029.541939, 568.559256), MAT_Vector3(89.438597, 0, 0))
  Node_ParseIniFile(node49, "osd/atl/atl_fregatte.osd")
  Body_SetFriendOrFoeID(node49, 0)
  Body_SetNameKey(node49, -1)
  Body_SetCargoKey(node49, -1, 0)
  Body_SetCargoKey(node49, -1, 1)
  Body_SetCargoKey(node49, -1, 2)
  Node_EnterSimulation(node49)
  Game_LoadProgress_Advance(node0)
  node50 = Node_CreateNode("nod_vessel", "atl_fregatte_2")
  Node_AddSon(node45, node50)
  Body_SetCS(node50, MAT_Vector3(379.999874, 3110.905259, 350), MAT_Vector3(-180, 0, 0))
  Node_ParseIniFile(node50, "osd/atl/atl_fregatte.osd")
  Body_SetFriendOrFoeID(node50, 0)
  Body_SetNameKey(node50, -1)
  Body_SetCargoKey(node50, -1, 0)
  Body_SetCargoKey(node50, -1, 1)
  Body_SetCargoKey(node50, -1, 2)
  Node_EnterSimulation(node50)
  Game_LoadProgress_Advance(node0)
  node51 = Node_CreateNode("nod_vessel", "atl_scout2_1")
  Node_AddSon(node45, node51)
  Body_SetCS(node51, MAT_Vector3(421.00186, 3166.396783, 350), MAT_Vector3(-178.130265, 0, 0))
  Node_ParseIniFile(node51, "osd/atl/atl_scout2.osd")
  Body_SetFriendOrFoeID(node51, 0)
  Body_SetNameKey(node51, -1)
  Body_SetCargoKey(node51, -1, 0)
  Body_SetCargoKey(node51, -1, 1)
  Body_SetCargoKey(node51, -1, 2)
  Node_EnterSimulation(node51)
  Game_LoadProgress_Advance(node0)
  node52 = Node_CreateNode("nod_vessel", "atl_scout2_2")
  Node_AddSon(node45, node52)
  Body_SetCS(node52, MAT_Vector3(320.701786, 3165.877677, 350), MAT_Vector3(-179.642077, 0, 0))
  Node_ParseIniFile(node52, "osd/atl/atl_scout2.osd")
  Body_SetFriendOrFoeID(node52, 0)
  Body_SetNameKey(node52, -1)
  Body_SetCargoKey(node52, -1, 0)
  Body_SetCargoKey(node52, -1, 1)
  Body_SetCargoKey(node52, -1, 2)
  Node_EnterSimulation(node52)
  Game_LoadProgress_Advance(node0)
  node53 = Node_CreateNode("nod_vessel", "gen_freighter2_1")
  Node_AddSon(node45, node53)
  Body_SetCS(node53, MAT_Vector3(471.672063, 3026.272542, 791.498215), MAT_Vector3(0, 0, 0))
  Node_ParseIniFile(node53, "osd/gen/gen_freighter2.osd")
  Body_SetFriendOrFoeID(node53, 0)
  Body_SetNameKey(node53, -1)
  Body_SetCargoKey(node53, -1, 0)
  Body_SetCargoKey(node53, -1, 1)
  Body_SetCargoKey(node53, -1, 2)
  Node_EnterSimulation(node53)
  Game_LoadProgress_Advance(node0)
  node54 = Node_CreateNode("nod_generic", "SSchiff_d")
  Node_AddSon(node44, node54)
  Body_SetCS(node54, MAT_Vector3(3642.365113, 1173.446438, 183.883545), MAT_Vector3(132.811891, -9.622757, 1.263346))
  Node_ParseIniFile(node54, "osd/des/des_jumpship_dam.osd")
  Body_SetFriendOrFoeID(node54, 2)
  Body_SetNameKey(node54, -1)
  Body_SetCargoKey(node54, -1, 0)
  Body_SetCargoKey(node54, -1, 1)
  Body_SetCargoKey(node54, -1, 2)
  Node_EnterSimulation(node54)
  Game_LoadProgress_Advance(node0)
  node55 = Node_CreateNode("NOD_Camera", "Camera")
  Node_AddSon(node0, node55)
  Camera_SetBackPlane(node55, 1024)
  Node_EnterSimulation(node55)
  Game_LoadProgress_Advance(node0)
  node56 = Node_CreateNode("NOD_Scenario", "stationcamera")
  Node_AddSon(node0, node56)
  Node_EnterSimulation(node56)
  Game_LoadProgress_Advance(node0)
  node57 = Node_CreateNode("NOD_Directory", "Light")
  Node_AddSon(node56, node57)
  Node_EnterSimulation(node57)
  Game_LoadProgress_Advance(node0)
  node58 = Node_CreateNode("NOD_Directory", "Navigation")
  Node_AddSon(node56, node58)
  Node_EnterSimulation(node58)
  Game_LoadProgress_Advance(node0)
  node59 = Node_CreateNode("NOD_Position", "MoveFrom")
  Node_AddSon(node58, node59)
  Position_SetPosition(node59, MAT_Vector3(38.007479, 2502.90059, 300))
  Position_SetRadius(node59, 20)
  Game_LoadProgress_Advance(node0)
  node60 = Node_CreateNode("NOD_Position", "LookFrom")
  Node_AddSon(node58, node60)
  Position_SetPosition(node60, MAT_Vector3(314.587511, 2820.724923, 300))
  Position_SetRadius(node60, 20)
  Game_LoadProgress_Advance(node0)
  node61 = Node_CreateNode("NOD_Position", "LookAt")
  Node_AddSon(node58, node61)
  Position_SetPosition(node61, MAT_Vector3(782.522167, 3294.333165, 800))
  Position_SetRadius(node61, 20)
  Game_LoadProgress_Advance(node0)
  node62 = Node_CreateNode("NOD_Directory", "Director")
  Node_AddSon(node56, node62)
  Node_EnterSimulation(node62)
  Game_LoadProgress_Advance(node0)
  node63 = Node_CreateNode("NOD_Director", "camera")
  Node_AddSon(node62, node63)
  Node_EnterSimulation(node63)
  Game_LoadProgress_Advance(node0)
  node64 = Node_CreateNode("NOD_Directory", "Trigger")
  Node_AddSon(node56, node64)
  Node_EnterSimulation(node64)
  Game_LoadProgress_Advance(node0)
  node65 = Node_CreateNode("NOD_Directory", "Object")
  Node_AddSon(node56, node65)
  Node_EnterSimulation(node65)
end
SetEnemyMatrixElement(0, 0, N)
SetEnemyMatrixElement(1, 0, F)
SetEnemyMatrixElement(2, 0, E)
SetEnemyMatrixElement(3, 0, E)
SetEnemyMatrixElement(4, 0, N)
SetEnemyMatrixElement(5, 0, N)
SetEnemyMatrixElement(6, 0, E)
SetEnemyMatrixElement(7, 0, N)
SetEnemyMatrixElement(8, 0, N)
SetEnemyMatrixElement(9, 0, N)
SetEnemyMatrixElement(10, 0, N)
SetEnemyMatrixElement(11, 0, N)
SetEnemyMatrixElement(12, 0, N)
SetEnemyMatrixElement(13, 0, N)
SetEnemyMatrixElement(14, 0, N)
SetEnemyMatrixElement(15, 0, N)
SetEnemyMatrixElement(0, 1, F)
SetEnemyMatrixElement(1, 1, N)
SetEnemyMatrixElement(2, 1, E)
SetEnemyMatrixElement(3, 1, E)
SetEnemyMatrixElement(4, 1, N)
SetEnemyMatrixElement(5, 1, N)
SetEnemyMatrixElement(6, 1, N)
SetEnemyMatrixElement(7, 1, N)
SetEnemyMatrixElement(8, 1, N)
SetEnemyMatrixElement(9, 1, N)
SetEnemyMatrixElement(10, 1, N)
SetEnemyMatrixElement(11, 1, N)
SetEnemyMatrixElement(12, 1, N)
SetEnemyMatrixElement(13, 1, N)
SetEnemyMatrixElement(14, 1, N)
SetEnemyMatrixElement(15, 1, N)
SetEnemyMatrixElement(0, 2, E)
SetEnemyMatrixElement(1, 2, E)
SetEnemyMatrixElement(2, 2, N)
SetEnemyMatrixElement(3, 2, F)
SetEnemyMatrixElement(4, 2, N)
SetEnemyMatrixElement(5, 2, N)
SetEnemyMatrixElement(6, 2, N)
SetEnemyMatrixElement(7, 2, N)
SetEnemyMatrixElement(8, 2, N)
SetEnemyMatrixElement(9, 2, N)
SetEnemyMatrixElement(10, 2, N)
SetEnemyMatrixElement(11, 2, N)
SetEnemyMatrixElement(12, 2, N)
SetEnemyMatrixElement(13, 2, N)
SetEnemyMatrixElement(14, 2, N)
SetEnemyMatrixElement(15, 2, N)
SetEnemyMatrixElement(0, 3, E)
SetEnemyMatrixElement(1, 3, E)
SetEnemyMatrixElement(2, 3, F)
SetEnemyMatrixElement(3, 3, N)
SetEnemyMatrixElement(4, 3, N)
SetEnemyMatrixElement(5, 3, N)
SetEnemyMatrixElement(6, 3, N)
SetEnemyMatrixElement(7, 3, N)
SetEnemyMatrixElement(8, 3, N)
SetEnemyMatrixElement(9, 3, N)
SetEnemyMatrixElement(10, 3, N)
SetEnemyMatrixElement(11, 3, N)
SetEnemyMatrixElement(12, 3, N)
SetEnemyMatrixElement(13, 3, N)
SetEnemyMatrixElement(14, 3, N)
SetEnemyMatrixElement(15, 3, N)
SetEnemyMatrixElement(0, 4, N)
SetEnemyMatrixElement(1, 4, N)
SetEnemyMatrixElement(2, 4, N)
SetEnemyMatrixElement(3, 4, N)
SetEnemyMatrixElement(4, 4, N)
SetEnemyMatrixElement(5, 4, N)
SetEnemyMatrixElement(6, 4, N)
SetEnemyMatrixElement(7, 4, N)
SetEnemyMatrixElement(8, 4, N)
SetEnemyMatrixElement(9, 4, N)
SetEnemyMatrixElement(10, 4, N)
SetEnemyMatrixElement(11, 4, N)
SetEnemyMatrixElement(12, 4, N)
SetEnemyMatrixElement(13, 4, N)
SetEnemyMatrixElement(14, 4, N)
SetEnemyMatrixElement(15, 4, N)
SetEnemyMatrixElement(0, 5, N)
SetEnemyMatrixElement(1, 5, N)
SetEnemyMatrixElement(2, 5, N)
SetEnemyMatrixElement(3, 5, N)
SetEnemyMatrixElement(4, 5, N)
SetEnemyMatrixElement(5, 5, N)
SetEnemyMatrixElement(6, 5, N)
SetEnemyMatrixElement(7, 5, N)
SetEnemyMatrixElement(8, 5, N)
SetEnemyMatrixElement(9, 5, N)
SetEnemyMatrixElement(10, 5, N)
SetEnemyMatrixElement(11, 5, N)
SetEnemyMatrixElement(12, 5, N)
SetEnemyMatrixElement(13, 5, N)
SetEnemyMatrixElement(14, 5, N)
SetEnemyMatrixElement(15, 5, N)
SetEnemyMatrixElement(0, 6, E)
SetEnemyMatrixElement(1, 6, N)
SetEnemyMatrixElement(2, 6, N)
SetEnemyMatrixElement(3, 6, N)
SetEnemyMatrixElement(4, 6, N)
SetEnemyMatrixElement(5, 6, N)
SetEnemyMatrixElement(6, 6, N)
SetEnemyMatrixElement(7, 6, N)
SetEnemyMatrixElement(8, 6, N)
SetEnemyMatrixElement(9, 6, N)
SetEnemyMatrixElement(10, 6, N)
SetEnemyMatrixElement(11, 6, N)
SetEnemyMatrixElement(12, 6, N)
SetEnemyMatrixElement(13, 6, N)
SetEnemyMatrixElement(14, 6, N)
SetEnemyMatrixElement(15, 6, N)
SetEnemyMatrixElement(0, 7, N)
SetEnemyMatrixElement(1, 7, N)
SetEnemyMatrixElement(2, 7, N)
SetEnemyMatrixElement(3, 7, N)
SetEnemyMatrixElement(4, 7, N)
SetEnemyMatrixElement(5, 7, N)
SetEnemyMatrixElement(6, 7, N)
SetEnemyMatrixElement(7, 7, N)
SetEnemyMatrixElement(8, 7, N)
SetEnemyMatrixElement(9, 7, N)
SetEnemyMatrixElement(10, 7, N)
SetEnemyMatrixElement(11, 7, N)
SetEnemyMatrixElement(12, 7, N)
SetEnemyMatrixElement(13, 7, N)
SetEnemyMatrixElement(14, 7, N)
SetEnemyMatrixElement(15, 7, N)
SetEnemyMatrixElement(0, 8, N)
SetEnemyMatrixElement(1, 8, N)
SetEnemyMatrixElement(2, 8, N)
SetEnemyMatrixElement(3, 8, N)
SetEnemyMatrixElement(4, 8, N)
SetEnemyMatrixElement(5, 8, N)
SetEnemyMatrixElement(6, 8, N)
SetEnemyMatrixElement(7, 8, N)
SetEnemyMatrixElement(8, 8, N)
SetEnemyMatrixElement(9, 8, N)
SetEnemyMatrixElement(10, 8, N)
SetEnemyMatrixElement(11, 8, N)
SetEnemyMatrixElement(12, 8, N)
SetEnemyMatrixElement(13, 8, N)
SetEnemyMatrixElement(14, 8, N)
SetEnemyMatrixElement(15, 8, N)
SetEnemyMatrixElement(0, 9, N)
SetEnemyMatrixElement(1, 9, N)
SetEnemyMatrixElement(2, 9, N)
SetEnemyMatrixElement(3, 9, N)
SetEnemyMatrixElement(4, 9, N)
SetEnemyMatrixElement(5, 9, N)
SetEnemyMatrixElement(6, 9, N)
SetEnemyMatrixElement(7, 9, N)
SetEnemyMatrixElement(8, 9, N)
SetEnemyMatrixElement(9, 9, N)
SetEnemyMatrixElement(10, 9, N)
SetEnemyMatrixElement(11, 9, N)
SetEnemyMatrixElement(12, 9, N)
SetEnemyMatrixElement(13, 9, N)
SetEnemyMatrixElement(14, 9, N)
SetEnemyMatrixElement(15, 9, N)
SetEnemyMatrixElement(0, 10, N)
SetEnemyMatrixElement(1, 10, N)
SetEnemyMatrixElement(2, 10, N)
SetEnemyMatrixElement(3, 10, N)
SetEnemyMatrixElement(4, 10, N)
SetEnemyMatrixElement(5, 10, N)
SetEnemyMatrixElement(6, 10, N)
SetEnemyMatrixElement(7, 10, N)
SetEnemyMatrixElement(8, 10, N)
SetEnemyMatrixElement(9, 10, N)
SetEnemyMatrixElement(10, 10, N)
SetEnemyMatrixElement(11, 10, N)
SetEnemyMatrixElement(12, 10, N)
SetEnemyMatrixElement(13, 10, N)
SetEnemyMatrixElement(14, 10, N)
SetEnemyMatrixElement(15, 10, N)
SetEnemyMatrixElement(0, 11, N)
SetEnemyMatrixElement(1, 11, N)
SetEnemyMatrixElement(2, 11, N)
SetEnemyMatrixElement(3, 11, N)
SetEnemyMatrixElement(4, 11, N)
SetEnemyMatrixElement(5, 11, N)
SetEnemyMatrixElement(6, 11, N)
SetEnemyMatrixElement(7, 11, N)
SetEnemyMatrixElement(8, 11, N)
SetEnemyMatrixElement(9, 11, N)
SetEnemyMatrixElement(10, 11, N)
SetEnemyMatrixElement(11, 11, N)
SetEnemyMatrixElement(12, 11, N)
SetEnemyMatrixElement(13, 11, N)
SetEnemyMatrixElement(14, 11, N)
SetEnemyMatrixElement(15, 11, N)
SetEnemyMatrixElement(0, 12, N)
SetEnemyMatrixElement(1, 12, N)
SetEnemyMatrixElement(2, 12, N)
SetEnemyMatrixElement(3, 12, N)
SetEnemyMatrixElement(4, 12, N)
SetEnemyMatrixElement(5, 12, N)
SetEnemyMatrixElement(6, 12, N)
SetEnemyMatrixElement(7, 12, N)
SetEnemyMatrixElement(8, 12, N)
SetEnemyMatrixElement(9, 12, N)
SetEnemyMatrixElement(10, 12, N)
SetEnemyMatrixElement(11, 12, N)
SetEnemyMatrixElement(12, 12, N)
SetEnemyMatrixElement(13, 12, N)
SetEnemyMatrixElement(14, 12, N)
SetEnemyMatrixElement(15, 12, N)
SetEnemyMatrixElement(0, 13, N)
SetEnemyMatrixElement(1, 13, N)
SetEnemyMatrixElement(2, 13, N)
SetEnemyMatrixElement(3, 13, N)
SetEnemyMatrixElement(4, 13, N)
SetEnemyMatrixElement(5, 13, N)
SetEnemyMatrixElement(6, 13, N)
SetEnemyMatrixElement(7, 13, N)
SetEnemyMatrixElement(8, 13, N)
SetEnemyMatrixElement(9, 13, N)
SetEnemyMatrixElement(10, 13, N)
SetEnemyMatrixElement(11, 13, N)
SetEnemyMatrixElement(12, 13, N)
SetEnemyMatrixElement(13, 13, N)
SetEnemyMatrixElement(14, 13, N)
SetEnemyMatrixElement(15, 13, N)
SetEnemyMatrixElement(0, 14, N)
SetEnemyMatrixElement(1, 14, N)
SetEnemyMatrixElement(2, 14, N)
SetEnemyMatrixElement(3, 14, N)
SetEnemyMatrixElement(4, 14, N)
SetEnemyMatrixElement(5, 14, N)
SetEnemyMatrixElement(6, 14, N)
SetEnemyMatrixElement(7, 14, N)
SetEnemyMatrixElement(8, 14, N)
SetEnemyMatrixElement(9, 14, N)
SetEnemyMatrixElement(10, 14, N)
SetEnemyMatrixElement(11, 14, N)
SetEnemyMatrixElement(12, 14, N)
SetEnemyMatrixElement(13, 14, N)
SetEnemyMatrixElement(14, 14, N)
SetEnemyMatrixElement(15, 14, N)
SetEnemyMatrixElement(0, 15, N)
SetEnemyMatrixElement(1, 15, N)
SetEnemyMatrixElement(2, 15, N)
SetEnemyMatrixElement(3, 15, N)
SetEnemyMatrixElement(4, 15, N)
SetEnemyMatrixElement(5, 15, N)
SetEnemyMatrixElement(6, 15, N)
SetEnemyMatrixElement(7, 15, N)
SetEnemyMatrixElement(8, 15, N)
SetEnemyMatrixElement(9, 15, N)
SetEnemyMatrixElement(10, 15, N)
SetEnemyMatrixElement(11, 15, N)
SetEnemyMatrixElement(12, 15, N)
SetEnemyMatrixElement(13, 15, N)
SetEnemyMatrixElement(14, 15, N)
SetEnemyMatrixElement(15, 15, N)
S_o30 = { [nil] = {}, Start = function(L0)

end }
o65 = FormationLib.CreateFormation("InverseTriangle", "", "", "", 50, 30)
S_o66 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Node_LeaveSimulation(L0.Node)
  CallFunction(o66, "Code1")
end, Code1 = function(L0)
  L0["CodeIndex"] = 1
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
  else
    CallFunction(o66, "Code2")
  end
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    DipolLib.InUtero_Normal(L0, "Code3")
  else
    CallFunction(o66, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  SensorLib.ActivateAvpSensorComplex(L0, "medium", "wng", "", "", "", False, False, True)
  CallFunction(o66, "Code4")
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
  else
    CallFunction(o66, "Code5")
  end
end, Code5 = function(L0)
  L0["CodeIndex"] = 5
  Node_LeaveSimulation(L0.Node)
  CallFunction(o66, "Code6")
end, Code6 = function(L0)
  L0["CodeIndex"] = 6
end, CheckCondition = function(L0)
  if not (L0.CodeIndex < 1) then
    if not (L0.CodeIndex >= 2) then
      L1 = 0
    end
  end
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o72 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Node_LeaveSimulation(L0.Node)
  CallFunction(o72, "Code1")
end, Code1 = function(L0)
  L0["CodeIndex"] = 1
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
  else
    CallFunction(o72, "Code2")
  end
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    DipolLib.InUtero_Normal(L0, "Code3")
  else
    CallFunction(o72, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  SensorLib.ActivateAvpSensorComplex(L0, "medium", "HelpTran", "", "", "", False, False, True)
  CallFunction(o72, "Code4")
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
  else
    CallFunction(o72, "Code5")
  end
end, Code5 = function(L0)
  L0["CodeIndex"] = 5
  Node_LeaveSimulation(L0.Node)
  CallFunction(o72, "Code6")
end, Code6 = function(L0)
  L0["CodeIndex"] = 6
end, CheckCondition = function(L0)
  if not (L0.CodeIndex < 1) then
    if not (L0.CodeIndex >= 2) then
      L1 = 0
    end
  end
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o78 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o78, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o78, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o124 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o124, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o124, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o170 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o170, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o170, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o216 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o216, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o216, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o262 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o262, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o262, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    MiscLib.MilkRunGoto(L0, { o64, { {}, "Goto", "/Scenario_Dynamic/Navigation/FregattePath_1", 0.5, 1 } }, o65, "/Scenario_Dynamic/Navigation/FightArea_1", 0, "", "", "", "", 0, 1, True, "Code4")
  else
    CallFunction(o262, "Code4")
  end
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o309 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o309, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o309, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    MiscLib.MilkRunGoto(L0, { o64, { {}, "Goto", "/Scenario_Dynamic/Navigation/FregattePath_1", 0.5, 1 } }, o65, "/Scenario_Dynamic/Navigation/FightArea_1", 0, "", "", "", "", 0, 1, True, "Code4")
  else
    CallFunction(o309, "Code4")
  end
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o356 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o356, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o356, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    MiscLib.MilkRunGoto(L0, { o64, { {}, "Goto", "/Scenario_Dynamic/Navigation/FregattePath_1", 0.5, 1 } }, o65, "/Scenario_Dynamic/Navigation/FightArea_1", 0, "", "", "", "", 0, 1, True, "Code4")
  else
    CallFunction(o356, "Code4")
  end
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o403 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Vessel_CollisionObjects(L0.Node, 0)
  Vessel_CollisionTerrain(L0.Node, 0)
  CallFunction(o403, "Code2")
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    { L0, { {}, "DeactivateAvoidance" } }("Code3")
  else
    CallFunction(o403, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o449 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Node_LeaveSimulation(L0.Node)
  CallFunction(o449, "Code1")
end, Code1 = function(L0)
  L0["CodeIndex"] = 1
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
  else
    CallFunction(o449, "Code2")
  end
end, Code2 = function(L0)
  L0["CodeIndex"] = 2
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    DipolLib.InUtero_Normal(L0, "Code3")
  else
    CallFunction(o449, "Code3")
  end
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  Body_SetEmpShield(L0.Node, 1)
  CallFunction(o449, "Code4")
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
end, CheckCondition = function(L0)
  if not (L0.CodeIndex < 1) then
    if not (L0.CodeIndex >= 2) then
      L1 = 0
    end
  end
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
S_o484 = { [nil] = {}, Start = function(L0)

end }
S_o485 = { [nil] = {}, Start = function(L0)

end }
S_o486 = { [nil] = {}, Start = function(L0)

end }
S_o487 = { [nil] = {}, Start = function(L0)

end }
S_o488 = { [nil] = {}, Start = function(L0)
  L0["CodeIndex"] = 0
  CallFunction(L0.Thread, "Code0")
end, Code0 = function(L0)
  L0["CodeIndex"] = 0
  Camera_MoveTo(L0.Node, "/stationcamera/Navigation/MoveFrom", 0, "MMMN", 0)
  Camera_LookAt(L0.Node, "/stationcamera/Navigation/LookAt", 0, "MMMN", 0)
  Camera_RollTo(L0.Node, 0, 0, False)
  CallFunction(o488, "Code3")
end, Code3 = function(L0)
  L0["CodeIndex"] = 3
  if not (L0.CommandTable.CheckCondition(L0) ~= 1) then
    CameraLib.Wait(L0, 0.15, "Code4")
  else
    CallFunction(o488, "Code4")
  end
end, Code4 = function(L0)
  L0["CodeIndex"] = 4
  Camera_MoveTo(L0.Node, "/stationcamera/Navigation/LookFrom", 3, "MMMN", 0)
  CallFunction(o488, "Code5")
end, Code5 = function(L0)
  L0["CodeIndex"] = 5
end, CheckCondition = function(L0)
  return L1
end, ProcesseStateChange = function(L0)
  if not (L0.CommandTable.CheckCondition(L0) == 1) then
    StopAllActiveBehaviours_AndCall(L0, "Code" .. L0.CodeIndex + 1)
  end
end }
__StartUp = function()
  Game_LoadProgress_Enter(Node_Find("/"), 65)
  __InitLayout()
  __InitLayout = nil
  G_ScriptTimerThread = BindEasy(Node_Find("/"), "/script", C_ScriptTimer)
  o30 = BindEasy(Node_Find("/Scenario_Static/Object"), "SpStern_1", S_o30)
  o66 = BindEasy(Node_Find("/Scenario_Dynamic/Trigger"), "TriggerPresence_1", S_o66)
  o72 = BindEasy(Node_Find("/Scenario_Dynamic/Trigger"), "TriggerPresence_2", S_o72)
  o78 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "ent_jumpship_1", S_o78)
  o124 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "ent_jumpship_2", S_o124)
  o170 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "ent_jumpship_3", S_o170)
  o216 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "atl_fregatte_1", S_o216)
  o262 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "atl_fregatte_2", S_o262)
  o309 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "atl_scout2_1", S_o309)
  o356 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "atl_scout2_2", S_o356)
  o403 = BindEasy(Node_Find("/Scenario_Dynamic/Object/TRAFFIC"), "gen_freighter2_1", S_o403)
  o449 = BindEasy(Node_Find("/Scenario_Dynamic/Object"), "SSchiff_d", S_o449)
  o484 = BindEasy(Node_Find("/"), "Camera", S_o484)
  o485 = BindEasy(Node_Find("/stationcamera/Navigation"), "MoveFrom", S_o485)
  o486 = BindEasy(Node_Find("/stationcamera/Navigation"), "LookFrom", S_o486)
  o487 = BindEasy(Node_Find("/stationcamera/Navigation"), "LookAt", S_o487)
  o488 = BindEasy(Node_Find("/stationcamera/Director"), "camera", S_o488)
  o64 = { {}, o262, o309, o356 }()
  Game_LoadProgress_Leave(Node_Find("/"))
end
