-- dekompiliert aus dipol.sco
-- Quelle laut Bytecode: =(none)

SensorLib = LoadLib("Sensor")
DockLib = LoadLib("Dock")
LD_Jump = { [nil] = {}, Vessel_DipolInFinished = function(L0)
  L1 = GetInnerValue(L0, "LD_CallBack")
  RestoreModification(L0, "LD_Jump")
  CallFunction(L0.Thread, L1)
end, Vehicle_DipolInFinished = function(L0)
  L1 = GetInnerValue(L0, "LD_CallBack")
  RestoreModification(L0, "LD_Jump")
  CallFunction(L0.Thread, L1)
end, Turret_DipolInFinished = function(L0)
  L1 = GetInnerValue(L0, "LD_CallBack")
  RestoreModification(L0, "LD_Jump")
  CallFunction(L0.Thread, L1)
end, StopBehavior = function(L0)
  RestoreModification(L0, "LD_General")
end }
nil[nil] = { Dipol_Basis = {}, DipolJumpOut = function(L0, L1)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L1)
  Vessel_DipolOut(L0.Node)
  SetEngineValue(L0, "DipoledOut", 1)
  SetEngineValue(L0, "DestJump", 1)
  SetEngineValue(L0, "EmpJump", 1)
  SetEngineValue(L0, "DestEmpJump", 1)
end, LeaveSimulation = function(L0)
  Node_LeaveSimulation(L0.Node)
  SetEngineValue(L0, "DipoledOut", 1)
end, DipolJumpIn = function(L0, L1, L2)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L2)
  Vessel_DipolIn(L0.Node, L1)
end, JumpStop = function(L0)
  if IsNotLastModification(L0, "LD_Jump") then
    return
  end
  RestoreModification(L0, "LD_Jump")
end, InUtero_Normal = function(L0, L1)
  Node_EnterSimulation(L0.Node)
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  CallFunction(L0.Thread, L1)
end, InUtero_DipolIn = function(L0, L1)
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L1)
  Vessel_DipolIn(L0.Node, 0.1)
end, InUtero_VehicleDipolIn = function(L0, L1)
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L1)
  Vehicle_DipolIn(L0.Node)
end, InUtero_TurretDipolIn = function(L0, L1)
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L1)
  Turret_DipolIn(L0.Node, 0.1)
end, Turret_DipolJumpOut = function(L0, L1)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L1)
  Turret_DipolOut(L0.Node)
  SetEngineValue(L0, "DipoledOut", 1)
end, InUtero_DipolInRelative = function(L0, L1, L2, L3, L4, L5)
  Body_SetPosition(L0.Node, Body_GetPosition(L4) + MAT_Vector3(L1, L2, L3))
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  ApplyModification(L0, LD_Jump, "LD_Jump")
  StoreInnerValue(L0, "LD_CallBack", L5)
  Vessel_DipolIn(L0.Node, 0.1)
end, InUtero_Undock = function(L0, L1, L2)
  SetEngineValue(L0, "Born", 1)
  SensorLib.ActivateShotHitSensor(L0)
  SensorLib.ActivateShieldGuard(L0)
  DockLib.UndockOwn(L0, L1, L2)
end }
