-- dekompiliert aus dat\script\lib\dipol.sco
-- Quelle laut Bytecode: @Y:\AquaNox\dat\script\lib\dipol.scr
-- lua4dec.py, 2026-07-28

SensorLib = LoadLib("Sensor")
DockLib = LoadLib("Dock")
LD_Jump = { [nil] = {}, Vessel_DipolInFinished = function(State)
  callback = GetInnerValue(State, "LD_CallBack")
  RestoreModification(State, "LD_Jump")
  CallFunction(State.Thread, callback)
end, Vehicle_DipolInFinished = function(State)
  callback = GetInnerValue(State, "LD_CallBack")
  RestoreModification(State, "LD_Jump")
  CallFunction(State.Thread, callback)
end, StopBehavior = function(State)
  RestoreModification(State, "LD_General")
end }
nil[nil] = { Dipol_Basis = {}, DipolJumpOut = function(State, CallBack)
  ApplyModification(State, LD_Jump, "LD_Jump")
  StoreInnerValue(State, "LD_CallBack", CallBack)
  Vessel_DipolOut(State.Node)
  SetEngineValue(State, "DipoledOut", 1)
  SetEngineValue(State, "DestJump", 1)
  SetEngineValue(State, "EmpJump", 1)
  SetEngineValue(State, "DestEmpJump", 1)
end, LeaveSimulation = function(State)
  Node_LeaveSimulation(State.Node)
  SetEngineValue(State, "DipoledOut", 1)
end, DipolJumpIn = function(State, Time, CallBack)
  ApplyModification(State, LD_Jump, "LD_Jump")
  StoreInnerValue(State, "LD_CallBack", CallBack)
  Vessel_DipolIn(State.Node, Time)
end, JumpStop = function(State)
  if IsNotLastModification(State, "LD_Jump") then
    return
  end
  RestoreModification(State, "LD_Jump")
end, InUtero_Normal = function(State, CallBack)
  Node_EnterSimulation(State.Node)
  SetEngineValue(State, "Born", 1)
  SensorLib.ActivateShotHitSensor(State)
  SensorLib.ActivateShieldGuard(State)
  CallFunction(State.Thread, CallBack)
end, InUtero_DipolIn = function(State, CallBack)
  SetEngineValue(State, "Born", 1)
  SensorLib.ActivateShotHitSensor(State)
  SensorLib.ActivateShieldGuard(State)
  ApplyModification(State, LD_Jump, "LD_Jump")
  StoreInnerValue(State, "LD_CallBack", CallBack)
  Vessel_DipolIn(State.Node, 0.1)
end, InUtero_VehicleDipolIn = function(State, CallBack)
  Script_Log("Hier agekommen")
  SetEngineValue(State, "Born", 1)
  SensorLib.ActivateShotHitSensor(State)
  SensorLib.ActivateShieldGuard(State)
  ApplyModification(State, LD_Jump, "LD_Jump")
  StoreInnerValue(State, "LD_CallBack", CallBack)
  Vehicle_DipolIn(State.Node)
end, InUtero_DipolInRelative = function(State, XPos, YPos, ZPos, Reference, CallBack)
  Body_SetPosition(State.Node, Body_GetPosition(Reference) + MAT_Vector3(XPos, YPos, ZPos))
  SetEngineValue(State, "Born", 1)
  SensorLib.ActivateShotHitSensor(State)
  SensorLib.ActivateShieldGuard(State)
  ApplyModification(State, LD_Jump, "LD_Jump")
  StoreInnerValue(State, "LD_CallBack", CallBack)
  Vessel_DipolIn(State.Node, 0.1)
end, InUtero_Undock = function(State, DockMaster, CallBack)
  SetEngineValue(State, "Born", 1)
  SensorLib.ActivateShotHitSensor(State)
  SensorLib.ActivateShieldGuard(State)
  DockLib.UndockOwn(State, DockMaster, CallBack)
end }