-- dekompiliert aus dat\script\lib\vesselattack.sco
-- Quelle laut Bytecode: @Y:\AquaNox\dat\script\lib\vesselattack.scr
-- lua4dec.py, 2026-07-28

LibSync = LoadLib("Synchronization")
LibDipol = LoadLib("Dipol")
LVA_ClearArea = { [nil] = {}, LVA_Activate = function(State)
  Vessel_Patrol(State.Node, GetInnerValue(State, "VCA_Area"), GetInnerValue(State, "VCA_WaitingTime"), GetInnerValue(State, "VCA_Velocity"))
  StartEnemyPatrol(State, GetInnerValue(State, "VCA_Mode"), GetInnerValue(State, "VCA_DefaultRad"), GetInnerValue(State, "VCA_FirstPriority"), GetInnerValue(State, "VCA_SecondPriority"), GetInnerValue(State, "VCA_ThirdPriority"), GetInnerValue(State, "VCA_FourthPriority"), GetInnerValue(State, "VCA_Area"))
end, Vessel_AttackOver = function(State)
  Vessel_Patrol(State.Node, GetInnerValue(State, "VCA_Area"), GetInnerValue(State, "VCA_WaitingTime"), GetInnerValue(State, "VCA_Velocity"))
  Vessel_AttackTurretsStop(State.Node, "")
  StartEnemyPatrol(State, GetInnerValue(State, "VCA_Mode"), GetInnerValue(State, "VCA_DefaultRad"), GetInnerValue(State, "VCA_FirstPriority"), GetInnerValue(State, "VCA_SecondPriority"), GetInnerValue(State, "VCA_ThirdPriority"), GetInnerValue(State, "VCA_FourthPriority"), GetInnerValue(State, "VCA_Area"))
end, Body_EnemyArrivalPatrol = function(State)
  Vessel_AttackPatrol(State.Node, GetInnerValue(State, "VCA_DefaultRad"), GetInnerValue(State, "VCA_FirstPriority"), GetInnerValue(State, "VCA_SecondPriority"), GetInnerValue(State, "VCA_ThirdPriority"), GetInnerValue(State, "VCA_FourthPriority"), GetInnerValue(State, "VCA_Area"))
  Vessel_AttackTurrets(State.Node, "", GetInnerValue(State, "VCA_FirstPriority"), GetInnerValue(State, "VCA_SecondPriority"), GetInnerValue(State, "VCA_ThirdPriority"), GetInnerValue(State, "VCA_FourthPriority"))
end, Vessel_PatrolFinished = function(State)
  callback = GetInnerValue(State, "VCA_Callback")
  retValue = GetInnerValue(State, "VCA_Param")
  Vessel_AttackTurretsStop(State.Node, "")
  StopEnemyPatrol(State)
  RestoreModification(State, "LVA_ClearArea")
  CallFunction(State.Thread, callback, retValue)
end, StopBehavior = function(State)
  LibList.VesselAttack_Basis.ClearAreaStop(State)
end }
LVA_GuardArea = { [nil] = {}, LVA_Activate = function(State)
  Vessel_Patrol(State.Node, GetInnerValue(State, "VGA_PatrolArea"), -1, GetInnerValue(State, "VGA_Velocity"))
  StartEnemyPatrol(State, GetInnerValue(State, "VGA_Mode"), GetInnerValue(State, "VGA_Diameter"), GetInnerValue(State, "VGA_FirstPriority"), GetInnerValue(State, "VGA_SecondPriority"), GetInnerValue(State, "VGA_ThirdPriority"), GetInnerValue(State, "VGA_FourthPriority"), GetInnerValue(State, "VGA_TriggerArea"))
end, Vessel_AttackOver = function(State)
  Vessel_Patrol(State.Node, GetInnerValue(State, "VGA_PatrolArea"), -1, GetInnerValue(State, "VGA_Velocity"))
  Vessel_AttackTurretsStop(State.Node, "")
  StartEnemyPatrol(State, GetInnerValue(State, "VGA_Mode"), GetInnerValue(State, "VGA_Diameter"), GetInnerValue(State, "VGA_FirstPriority"), GetInnerValue(State, "VGA_SecondPriority"), GetInnerValue(State, "VGA_ThirdPriority"), GetInnerValue(State, "VGA_FourthPriority"), GetInnerValue(State, "VGA_TriggerArea"))
end, Body_EnemyArrivalPatrol = function(State)
  Vessel_AttackPatrol(State.Node, GetInnerValue(State, "VGA_Diameter"), GetInnerValue(State, "VGA_FirstPriority"), GetInnerValue(State, "VGA_SecondPriority"), GetInnerValue(State, "VGA_ThirdPriority"), GetInnerValue(State, "VGA_FourthPriority"), GetInnerValue(State, "VGA_FollowArea"))
  Vessel_AttackTurrets(State.Node, "", GetInnerValue(State, "VGA_FirstPriority"), GetInnerValue(State, "VGA_SecondPriority"), GetInnerValue(State, "VGA_ThirdPriority"), GetInnerValue(State, "VGA_FourthPriority"))
end, StopBehavior = function(State)
  LibList.VesselAttack_Basis.GuardAreaStop(State)
end }
LVA_GotoAttack = { [nil] = {}, LVA_Activate = function(State)
  Vessel_Goto(State.Node, GetInnerValue(State, "VGG_GotoPath"), GetInnerValue(State, "VGG_GotoSpeed"), GetInnerValue(State, "VGG_GotoInfluence"))
  StartEnemyPatrol(State, GetInnerValue(State, "VGG_Mode"), GetInnerValue(State, "VGG_AttackSphere"), GetInnerValue(State, "VGG_FirstPri"), GetInnerValue(State, "VGG_SecondPri"), GetInnerValue(State, "VGG_ThirdPri"), GetInnerValue(State, "VGG_FourthPri"), GetInnerValue(State, "VGG_AttackArea"))
end, Vessel_AttackOver = function(State)
  Vessel_AttackTurretsStop(State.Node, "")
  if not (GetInnerValue(State, "VGG_OldPosition")) then
    Vessel_Goto(State.Node, GetInnerValue(State, "VGG_GotoPath"), GetInnerValue(State, "VGG_GotoSpeed"), GetInnerValue(State, "VGG_GotoInfluence"))
  else
    Vessel_GotoFromPosition(State.Node, GetInnerValue(State, "VGG_GotoPath"), GetInnerValue(State, "VGG_OldPosition"), GetInnerValue(State, "VGG_GotoSpeed"), GetInnerValue(State, "VGG_GotoInfluence"))
  end
  StartEnemyPatrol(State, GetInnerValue(State, "VGG_Mode"), GetInnerValue(State, "VGG_AttackSphere"), GetInnerValue(State, "VGG_FirstPri"), GetInnerValue(State, "VGG_SecondPri"), GetInnerValue(State, "VGG_ThirdPri"), GetInnerValue(State, "VGG_FourthPri"), GetInnerValue(State, "VGG_AttackArea"))
end, Body_EnemyArrivalPatrol = function(State)
  Vessel_AttackPatrol(State.Node, GetInnerValue(State, "VGG_Diameter"), GetInnerValue(State, "VGG_FirstPri"), GetInnerValue(State, "VGG_SecondPri"), GetInnerValue(State, "VGG_ThirdPri"), GetInnerValue(State, "VGG_FourthPri"), GetInnerValue(State, "VGG_AttackArea"))
  Vessel_AttackTurrets(State.Node, "", GetInnerValue(State, "VGG_FirstPri"), GetInnerValue(State, "VGG_SecondPri"), GetInnerValue(State, "VGG_ThirdPri"), GetInnerValue(State, "VGG_FourthPri"))
end, Vessel_GotoPosReached = function(State, Path, Position)
  StoreInnerValue(State, "VGG_OldPosition", Position)
end, Vessel_GotoArrived = function(State, Path)
  Vessel_Goto(State.Node, GetInnerValue(State, "VGG_GotoPath"), GetInnerValue(State, "VGG_GotoSpeed"), GetInnerValue(State, "VGG_GotoInfluence"))
end, StopBehavior = function(State)
  LibList.VesselAttack_Basis.GotoAttackStop(State)
end }
LVA_GuardAreaRespawn = { [nil] = {}, LVA_Activate = function(State)
  LibList.VesselAttack_Basis.GuardArea(State, GetInnerValue(State, "VGAR_Mode"), GetInnerValue(State, "VGAR_PatrolArea"), GetInnerValue(State, "VGAR_TriggerArea"), GetInnerValue(State, "VGAR_FollowArea"), GetInnerValue(State, "VGAR_FirstPriority"), GetInnerValue(State, "VGAR_SecondPriority"), GetInnerValue(State, "VGAR_ThirdPriority"), GetInnerValue(State, "VGAR_FourthPriority"), GetInnerValue(State, "VGAR_Velocity"))
end, Body_ObjectDestroyed = function(State)
  LibList.VesselAttack_Basis.GuardAreaStop(State)
  Vessel_PseudoExplode(State.Node)
  Node_LeaveSimulation(State.Node)
  Body_SetKineticShield(State.Node, 0, 1)
  Body_SetEmpShield(State.Node, 1)
  Body_SetPosition(State.Node, GetInnerValue(State, "VGAR_Position"))
  Vessel_DipolIn(State.Node, 0.1)
end, Vessel_DipolInFinished = function(State)
  LibList.VesselAttack_Basis.GuardArea(State, GetInnerValue(State, "VGAR_Mode"), GetInnerValue(State, "VGAR_PatrolArea"), GetInnerValue(State, "VGAR_TriggerArea"), GetInnerValue(State, "VGAR_FollowArea"), GetInnerValue(State, "VGAR_FirstPriority"), GetInnerValue(State, "VGAR_SecondPriority"), GetInnerValue(State, "VGAR_ThirdPriority"), GetInnerValue(State, "VGAR_FourthPriority"), GetInnerValue(State, "VGAR_Velocity"))
end, StopBehavior = function(State)
  LibList.VesselAttack_Basis.GuardAreaRespawnStop(State)
end }
nil[nil] = { VesselAttack_Basis = {}, ClearAreaFrom = function(State, Mode, Area, TargetNode, WaitingTime, Velocity, Callback, Param)
  if not (Script_IsNodeRefValid(TargetNode)) then
    CallFunction(State.Thread, Callback, Param)
    return
  end
  ApplyModification(State, LVA_ClearArea, "LVA_ClearArea")
  StoreInnerValue(State, "VCA_Mode", Mode)
  StoreInnerValue(State, "VCA_Area", Area)
  StoreInnerValue(State, "VCA_DefaultRad", PatrolArea_GetDiameter(Node_Find(State.Node, Area)))
  StoreInnerValue(State, "VCA_WaitingTime", WaitingTime)
  StoreInnerValue(State, "VCA_FirstPriority", Node_GetName(TargetNode))
  StoreInnerValue(State, "VCA_SecondPriority", "")
  StoreInnerValue(State, "VCA_ThirdPriority", "")
  StoreInnerValue(State, "VCA_FourthPriority", "")
  StoreInnerValue(State, "VCA_Velocity", Velocity)
  StoreInnerValue(State, "VCA_Callback", Callback)
  StoreInnerValue(State, "VCA_Param", Param)
  CallFunction(State.Thread, "LVA_Activate", nil)
end, ClearAreaFromStop = function(State)
  if IsNotLastModification(State, "LVA_ClearArea") then
    return
  end
  StopEnemyPatrol(State)
  Vessel_AttackTurretsStop(State.Node)
  RestoreModification(State, "LVA_ClearArea")
end, ClearArea = function(State, Mode, Area, FirstPriority, SecondPriority, ThirdPriority, FourthPriority, WaitingTime, Velocity, Callback, Param)
  ApplyModification(State, LVA_ClearArea, "LVA_ClearArea")
  StoreInnerValue(State, "VCA_Area", Area)
  StoreInnerValue(State, "VCA_Mode", Mode)
  StoreInnerValue(State, "VCA_DefaultRad", PatrolArea_GetDiameter(Node_Find(State.Node, Area)))
  StoreInnerValue(State, "VCA_FirstPriority", FirstPriority)
  StoreInnerValue(State, "VCA_SecondPriority", SecondPriority)
  StoreInnerValue(State, "VCA_ThirdPriority", ThirdPriority)
  StoreInnerValue(State, "VCA_FourthPriority", FourthPriority)
  StoreInnerValue(State, "VCA_WaitingTime", WaitingTime)
  StoreInnerValue(State, "VCA_Velocity", Velocity)
  StoreInnerValue(State, "VCA_Callback", Callback)
  StoreInnerValue(State, "VCA_Param", Param)
  CallFunction(State.Thread, "LVA_Activate", nil)
end, ClearAreaStop = function(State)
  if IsNotLastModification(State, "LVA_ClearArea") then
    return
  end
  StopEnemyPatrol(State)
  Vessel_AttackTurretsStop(State.Node, "")
  RestoreModification(State, "LVA_ClearArea")
end, GuardArea = function(State, Mode, PatrolArea, TriggerArea, FollowArea, FirstPriority, SecondPriority, ThirdPriority, FourthPriority, Velocity)
  ApplyModification(State, LVA_GuardArea, "LVA_GuardArea")
  StoreInnerValue(State, "VGA_Mode", Mode)
  StoreInnerValue(State, "VGA_Diameter", PatrolArea_GetDiameter(Node_Find(State.Node, TriggerArea)))
  StoreInnerValue(State, "VGA_PatrolArea", PatrolArea)
  StoreInnerValue(State, "VGA_TriggerArea", TriggerArea)
  StoreInnerValue(State, "VGA_FollowArea", FollowArea)
  StoreInnerValue(State, "VGA_FirstPriority", FirstPriority)
  StoreInnerValue(State, "VGA_SecondPriority", SecondPriority)
  StoreInnerValue(State, "VGA_ThirdPriority", ThirdPriority)
  StoreInnerValue(State, "VGA_FourthPriority", FourthPriority)
  StoreInnerValue(State, "VGA_Velocity", Velocity)
  CallFunction(State.Thread, "LVA_Activate", nil)
end, GuardAreaStop = function(State)
  if IsNotLastModification(State, "LVA_GuardArea") then
    return
  end
  StopEnemyPatrol(State)
  Vessel_AttackTurretsStop(State.Node, "")
  RestoreModification(State, "LVA_GuardArea")
end, GotoAttack = function(State, Mode, GotoPath, GotoSpeed, GotoInfluence, AttackArea, AttackSphere, FirstPri, SecondPri, ThirdPri, FourthPri)
  ApplyModification(State, LVA_GotoAttack, "LVA_GotoAttack")
  StoreInnerValue(State, "VGG_Mode", Mode)
  StoreInnerValue(State, "VGG_Diameter", PatrolArea_GetDiameter(Node_Find(State.Node, AttackArea)))
  StoreInnerValue(State, "VGG_GotoSpeed", GotoSpeed)
  StoreInnerValue(State, "VGG_GotoPath", GotoPath)
  StoreInnerValue(State, "VGG_GotoInfluence", GotoInfluence)
  StoreInnerValue(State, "VGG_AttackArea", AttackArea)
  StoreInnerValue(State, "VGG_AttackSphere", AttackSphere)
  StoreInnerValue(State, "VGG_FirstPri", FirstPri)
  StoreInnerValue(State, "VGG_SecondPri", SecondPri)
  StoreInnerValue(State, "VGG_ThirdPri", ThirdPri)
  StoreInnerValue(State, "VGG_FourthPri", FourthPri)
  CallFunction(State.Thread, "LVA_Activate", nil)
end, GotoAttackStop = function(State)
  if IsNotLastModification(State, "LVA_GotoAttack") then
    return
  end
  StopEnemyPatrol(State)
  Vessel_AttackTurretsStop(State.Node, "")
  RestoreModification(State, "LVA_GotoAttack")
end, GuardAreaRespawn = function(State, Mode, PatrolArea, TriggerArea, FollowArea, FirstPriority, SecondPriority, ThirdPriority, FourthPriority, Velocity, Position)
  ApplyModification(State, LVA_GuardAreaRespawn, "LVA_GuardAreaRespawn")
  StoreInnerValue(State, "VGAR_Mode", Mode)
  StoreInnerValue(State, "VGAR_PatrolArea", PatrolArea)
  StoreInnerValue(State, "VGAR_TriggerArea", TriggerArea)
  StoreInnerValue(State, "VGAR_FollowArea", FollowArea)
  StoreInnerValue(State, "VGAR_FirstPriority", FirstPriority)
  StoreInnerValue(State, "VGAR_SecondPriority", SecondPriority)
  StoreInnerValue(State, "VGAR_ThirdPriority", ThirdPriority)
  StoreInnerValue(State, "VGAR_FourthPriority", FourthPriority)
  StoreInnerValue(State, "VGAR_Velocity", Velocity)
  StoreInnerValue(State, "VGAR_Position", Position_GetPosition(Node_Find(State.Node, Position)))
  StartShieldGuard(State)
  CallFunction(State.Thread, "LVA_Activate", nil)
end, GuardAreaRespawnStop = function(State)
  LibList.VesselAttack_Basis.GuardAreaStop(State)
  if IsNotLastModification(State, "LVA_GuardAreaRespawn") then
    return
  end
  StopShieldGuard(State)
  RestoreModification(State, "LVA_GuardAreaRespawn")
end }